name: Deploy Hugo Demo

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
  # Allows manual workflow runs
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Clone repository
        uses: actions/checkout@v3

      - name: 🔄 Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: 📦 Install Dart Sass
        run: sudo snap install dart-sass

      - name: Update Hugo Modules
        run: hugo mod get -u

      - name: 📦 Install dependencies
        run: hugo mod tidy 

      - name: 🚀 Build Hugo site
        run: hugo --minify -s exampleSite -d public

      - name: 📤 Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public